[tool.isort]
profile = "black"

[tool.black]
line-length = 150

[tool.pylint.messages_control]
max-line-length = 150
disable = [
  "duplicate-code",
  "fixme",
  "missing-class-docstring",
  "missing-function-docstring",
  "missing-module-docstring",
  "no-else-return",
  "unused-wildcard-import",
  "wildcard-import"
]
