version: 2.1

workflows:
  version: 2
  circleci:
    jobs:
      - azlint
      - install:
          matrix:
            parameters:
              image:
                - debian:11.8
                - debian:12.2
                - ubuntu:22.04
                - ubuntu:rolling

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint:0.6.11
    steps:
      - checkout
      - run: |
          if [ "$CIRCLE_BRANCH" = main ]; then
            azlint
          else
            azlint --only-changed
          fi

  install:
    parameters:
      image:
        type: string
    docker:
      - image: "<< parameters.image >>"
    steps:
      - checkout
      - run: apt-get update && apt-get install --yes curl python3 python3-pip python3-venv
      - run: curl -fsSL https://deb.nodesource.com/setup_current.x | bash - && apt-get install -y nodejs
      - run: make bootstrap
      - run: make build
      - run: make install
      - run: sh setup/test.sh
