version: 2.1

workflows:
  version: 2
  circleci:
    jobs:
      - azlint
      - install:
          matrix:
            parameters:
              image:
                - debian:11.7
                - ubuntu:22.04

jobs:
  azlint:
    docker:
      - image: matejkosiarcik/azlint:0.4.5
    steps:
      - checkout
      - run: find .config -type f -exec sh -c 'ln -s "$0" "$(basename "$0")"' {} \; # TODO: Remove
      - run: |
          if [ "$CIRCLE_BRANCH" = main ]; then
            azlint
          else
            azlint --only-changed
          fi

  install:
    parameters:
      image:
        type: string
    docker:
      - image: "<< parameters.image >>"
    steps:
      - checkout
      - run: apt-get update && apt-get install --yes python3 python3-pip python3-venv
      - run: make bootstrap
      - run: make install
