# Taps
tap "caskroom/cask"
brew "mas"

# shells
brew "dash"
brew "ksh"
brew "mksh"
brew "yash"
brew "zsh"
cask "iterm2"
cask "powershell"

# languages
brew "node"
brew "php"
brew "python@2"
brew "python@3"
brew "ruby"
cask "java"

# package managers
brew "carthage"
brew "composer"

# generators
brew "sourcery"
brew "swiftgen"
brew "xcodegen"

# linters/formatters
brew "shellcheck"
brew "shfmt"
brew "svgcleaner"
brew "swiftlint"
brew "tidy-html5"
brew "yamllint"

# toolings
brew "autoconf"
brew "cmake"
brew "gcc"
brew "plantuml"

# services
brew "circleci"
brew "hub"

# image manipulation
brew "imagemagick", args: ["with-librsvg"]
brew "librsvg"
brew "svg2pdf"
brew "svg2png"
cask "gimp"
cask "inkscape"

# browsers
brew "elinks"
brew "lynx"
cask "firefox"
cask "google-chrome"
cask "opera"
cask "tor-browser"
cask "vivaldi"

# editors/IDEs
cask "android-studio"
cask "jetbrains-toolbox"
cask "mactex"
cask "sublime-text"
cask "visual-studio-code"

# git UIs
brew "tig"
cask "meld"
cask "sourcetree"

# media
brew "youtube-dl"
cask "handbrake"
cask "vlc"

# communication
cask "microsoft-teams"
cask "skype"
cask "slack"

# user tools
brew "cloc"
brew "cputhrottle"
brew "tree"
brew "wine"
brew "winetricks"
cask "coconutbattery"
cask "duet"
cask "flux"
cask "spectacle"
cask "transmission"
cask "virtualbox-extension-pack"
cask "virtualbox"

# dev/other
brew "aspell"
brew "cliclick"
brew "docker-completion"
brew "docker"
brew "duti"
brew "lftp"
brew "ncurses"
brew "openssl"
brew "redir"
brew "wget"
cask "docker"
cask "free-ruler"
cask "xquartz"
