# Taps
tap "caskroom/cask"
brew "mas"

# shells/terminals
brew "dash"
brew "ksh"
brew "mksh"
brew "tmux"
brew "yash"
brew "zsh"
cask "iterm2"
cask "powershell"

# languages
brew "node"
brew "php", restart_service: true
brew "python@2"
brew "python@3"
brew "ruby"
cask "java"

# additional languages
brew "jython"
brew "micropython"
brew "pypy"
brew "pypy3"

# languages support
brew "pipenv"
brew "pyenv"
brew "nvm"
brew "rbenv"

# package managers
brew "carthage"
brew "cocoapods"
brew "composer"

# generators
brew "sourcery"
brew "swiftgen"
brew "xcodegen"

# linters/formatters
brew "shellcheck"
brew "shfmt"
brew "svgcleaner"
brew "swiftlint"
brew "tidy-html5"
brew "yamllint"

# toolings
brew "autoconf"
brew "cmake"
brew "docker"
brew "emscripten"
brew "gcc"
brew "plantuml"
cask "docker"

# dev/other
brew "circleci"
brew "lftp"
brew "libssh2"
brew "ncurses"
brew "openssl"
brew "travis"
brew "wget"
cask "xquartz"

# image manipulation
brew "cairo"
brew "imagemagick", args: ["with-librsvg"]
brew "librsvg"
brew "openjpeg"
brew "svg2pdf"
brew "svg2png"
cask "gimp"
cask "inkscape"

# browsers
brew "elinks"
brew "geckodriver"
brew "lynx"
cask "chromedriver"
cask "firefox"
cask "google-chrome"
cask "opera"
cask "operadriver"
cask "tor-browser"
cask "vivaldi"

# editors/IDEs
cask "android-studio"
cask "atom"
cask "jetbrains-toolbox"
cask "mactex"
cask "sublime-text"
cask "visual-studio-code"

# version control
brew "mercurial"
brew "tig"
cask "sourcetree"

# media
brew "ffmpeg"
brew "youtube-dl"
cask "handbrake"
cask "vlc"

# communication
cask "microsoft-teams"
cask "skype"
cask "slack"

# user tools
brew "aspell"
brew "cliclick"
brew "cloc"
brew "duti"
brew "tree"
brew "wine"
brew "winetricks"
cask "coconutbattery"
cask "duet"
cask "flux"
cask "free-ruler"
cask "spectacle"
cask "transmission"
cask "virtualbox-extension-pack"
cask "virtualbox"
