exclude = [
  '^https://bevry\.me', # Frequent timeouts
  '^https://www.patreon.com/feross', # 403s
  '^shivammathur/setup-php@.+$', # Invalid email address
  '^https?://localhost', # Localhost
  '^https?://[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+', # IPs
  '^https?://.*\.matejhome\.com', # Private domain
  '^https?://.*', # Everything else
]
