# Taps
tap "caskroom/cask"
brew "mas"

# shells/terminals
brew "dash"
brew "ksh"
brew "mksh"
brew "tmux"
brew "yash"
brew "zsh"
cask "iterm2"
cask "powershell"

# languages
brew "gcc"
brew "node"
brew "php", restart_service: true
brew "python@2"
brew "python@3"
brew "ruby"
cask "adoptopenjdk"
# cask "java"

# additional languages
# brew "emscripten"
brew "jython"
brew "micropython"
brew "pypy"
brew "pypy3"

# languages support
brew "pipenv"
brew "pyenv"
brew "nvm"
brew "rbenv"

# package managers
brew "carthage"
brew "cocoapods"
brew "composer"

# generators
brew "autoconf"
brew "cmake"
brew "sourcery"
brew "swiftgen"
brew "xcodegen"

# linters/formatters
brew "shellcheck"
brew "shfmt"
brew "svgcleaner"
brew "swiftlint"
brew "tidy-html5"
brew "yamllint"

# dev/other
brew "circleci"
brew "cloc"
brew "lftp"
brew "libssh2"
brew "ncurses"
brew "openssl"
brew "plantuml"
brew "travis"
brew "wget"
cask "xquartz"

# editors/IDEs
cask "android-studio"
cask "atom"
cask "jetbrains-toolbox"
cask "mactex"
cask "sublime-text"
cask "visual-studio-code"

# version control
brew "mercurial"
brew "tig"
cask "sourcetree"

# user tools
brew "aspell"
# brew "cliclick"
brew "duti"
brew "tree"
cask "coconutbattery"
cask "duet"
cask "flux"
# cask "free-ruler"
cask "spectacle"
cask "transmission"
