# config
brew "mas"

### Development ###

# shells
brew "dash"
brew "ksh"
brew "mksh"
brew "tmux"
brew "yash"
brew "zsh"
cask "powershell"

# languages
brew "gcc"
brew "gdb"
brew "node"
brew "php", restart_service: true
brew "python"
brew "ruby"
brew "rustup-init"
cask "adoptopenjdk"
# cask "java" # sometimes collides with openjdk

# additional languages
# brew "emscripten" # better to install by hand
# brew "jython"
# brew "micropython"
# brew "pypy"
# brew "pypy3"

# languages support
# brew "pipenv"
brew "pyenv"
brew "nvm"
brew "rbenv"

# package managers
brew "carthage"
brew "composer"
# brew "mint"

# generators
brew "autoconf"
brew "cmake"
# brew "sourcery"
# brew "swiftgen"
# brew "xcodegen"

# linters/formatters
# brew "shfmt"
# brew "swiftlint"
brew "tidy-html5"
brew "clang-format"

# other
brew "circleci"
brew "cloc"
brew "lftp"
brew "libssh2"
brew "ncurses"
brew "openssl"
brew "plantuml"
brew "wget"
cask "xquartz"

# brew "docker"
cask "docker"

# version control
brew "mercurial"
brew "tig"
cask "sourcetree"

### Text editing ###

# editors/IDEs
# cask "android-studio"
cask "atom"
cask "jetbrains-toolbox"
cask "mactex"
cask "sublime-text"
cask "visual-studio-code"

# user tools
brew "aspell"
brew "cliclick"
brew "duti"
brew "tree"
cask "coconutbattery"
cask "duet"
cask "flux"
cask "free-ruler"
cask "spectacle"
cask "transmission"

### Web Browsers ###

# terminal
brew "elinks"
brew "lynx"

# gui
cask "firefox"
cask "google-chrome"
cask "opera"
cask "tor-browser"
cask "vivaldi"
cask "brave-browser"

# drivers
brew "geckodriver"
cask "chromedriver"
cask "operadriver"

### Media ###

# media creation
brew "cairo"
brew "imagemagick"
brew "librsvg"
brew "openjpeg"
brew "svg2pdf"
brew "svg2png"
cask "gimp"
cask "inkscape"

# media consumption
brew "ffmpeg"
brew "youtube-dl"
cask "handbrake"
cask "vlc"

### User tools ###
# cask "microsoft-teams"
cask "skype"
# cask "slack"
# cask "mattermost"
cask "wine-stable"
brew "winetricks"
cask "ferdi"

### Other taps ###
# tap "kylef/formulae"
# brew "swiftenv"

tap "heroku/brew"
brew "heroku"

# Install following casks manually (because they require additional permissions (probably because of kernel extensions))
# Then go to (System Preferences > Security & Privacy > General) to resolve permissions after installation
# cask "virtualbox"
# cask "virtualbox-extension-pack"
