name: Lint

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  azlint:
    name: AZLint
    runs-on: ubuntu-latest
    container:
      image: matejkosiarcik/azlint:0.6.6
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
        with:
          fetch-depth: 0 # Full git history is needed to get a proper list of changed files

      - name: Run AZLint
        run: |
          # TODO: Remove overrides
          export VALIDATE_SHELLHARDEN=false
          export VALIDATE_SHELLCHECK=false
          export VALIDATE_SHELL_DRY_RUN=false
          export VALIDATE_PROSELINT=false
          if [ "$GITHUB_REF_NAME" = main ]; then
            azlint
          else
            azlint # --only-changed # TODO: Fix
          fi
