name: Test

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    name: Build and Test (${{ matrix.os }})
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7

      - name: Setup Python
        uses: actions/setup-python@v5.1.1
        with:
          python-version: 3.x

      - name: Setup NodeJS
        uses: actions/setup-node@v4.0.3
        with:
          node-version: latest

      # - name: Install HomeBrew dependencies
      #   if: ${{ matrix.os == 'macos-latest' }}
      #   shell: bash
      #   run: |
      #     brew install platypus # TODO: Reenable platypus after https://github.com/sveinbjornt/Platypus/issues/262

      - name: Install project dependencies
        shell: bash
        run: make bootstrap

      - name: Build
        shell: bash
        env:
          CI: 1
        run: make build

      - name: Instal project to current system
        shell: bash
        env:
          CI: 1
        run: make install

      - name: Test project installation
        shell: bash
        run: sh .ci-utils/postinstall-test.sh
