name: Test

permissions: read-all

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    name: Test
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Python
        uses: actions/setup-python@v5.0.0
        with:
          python-version: 3.x

      - uses: actions/setup-node@v4.0.1
        with:
          node-version: latest

      - run: make bootstrap
        shell: bash
      - run: make build
        shell: bash
      - run: make install
        shell: bash

      - run: sh utils/postinstall-test.sh
